# These are supported funding model platforms
# Replace placeholder values with your actual usernames/links.
# Keep only the lines you use.

github: [SlothUIM]                # Up to 4 GitHub Sponsors-enabled usernames
patreon: your_patreon_username    # Single Patreon username
open_collective: your_collective  # Single Open Collective username
ko_fi: your_kofi_username         # Single Ko-fi username
tidelift: platform/name           # e.g., npm/babel
community_bridge: your_project    # e.g., cloud-foundry
liberapay: your_liberapay         # Single Liberapay username
issuehunt: your_issuehunt         # Single IssueHunt username
lfx_crowdfunding: your_lfx_proj   # e.g., cloud-foundry
polar: your_polar_username        # Single Polar username
buy_me_a_coffee: your_bmac        # Single Buy Me a Coffee username
thanks_dev: your_thanks_dev       # Single thanks.dev username
custom:                           # Up to 4 custom sponsorship URLs
  - https://paypal.me/YourPayPal
  - https://your-site.example.com/sponsor
