# These are supported funding model platforms
# Replace placeholder values with your actual usernames/links.
# Keep only the lines you use.

github: [SlothUIM]                # Up to 4 GitHub Sponsors-enabled usernames
patreon: whitelavendr    # Single Patreon username
buy_me_a_coffee: slothearth        # Single Buy Me a Coffee username
custom:                           # Up to 4 custom sponsorship URLs
  - https://paypal.me/whitelav
